# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 15:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('Ab', 'Abacus'), ('Vm', 'Vedic Maths'), ('En', 'English Grammar'), ('HC', 'Handwriting / Calligraphy'), ('AD', 'Art and Craft / Drawing'), ('Tu', 'Tuition')], max_length=2)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 11, 2, 15, 3, 44, 24672, tzinfo=utc))),
                ('amount', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10)),
                ('doe', models.DateField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 3, 44, 23178, tzinfo=utc), null=True)),
                ('dob', models.DateField(blank=True, default=datetime.datetime(2017, 11, 2, 15, 3, 44, 23213, tzinfo=utc), null=True)),
                ('clas', models.IntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('adhaar', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mobile_f', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')])),
                ('occupation_father', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mobile_m', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')])),
                ('occupation_mother', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Student'),
        ),
    ]
