# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ci',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
