# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20170513_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='month',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='year',
        ),
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 15, 9, 10, 31, 923295)),
        ),
    ]
