# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-03 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20170515_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adhaar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='annual_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 3, 18, 44, 25, 697497, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='doe',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 3, 18, 44, 35, 289493, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_f',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_m',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='occupation_father',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='occupation_mother',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('Ab', 'Abacus'), ('Vm', 'Vedic Maths'), ('En', 'English Grammar'), ('HC', 'Handwriting / Calligraphy'), ('AD', 'Art and Craft / Drawing'), ('Tu', 'Tuition')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 3, 18, 43, 53, 709749, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='ci',
            field=models.CharField(choices=[('1', 'Monica Katyal'), ('2', 'Vimmi Arora'), ('3', 'Savitri Bisht'), ('4', 'Raghav Kumar'), ('5', 'Kavita Bisht'), ('6', 'Sarita Garg'), ('7', 'Aanchal Juneja'), ('8', 'Bhawna Goel'), ('9', 'Deepa Arora'), ('10', 'Disha Rughwani'), ('11', 'Gunjan Chaddha'), ('12', 'Harshita'), ('13', 'Kanika Gupta'), ('14', 'Kuldeep Kaur'), ('15', 'Madhuri Bindra'), ('16', 'Neeraj Sharma'), ('17', 'Nisha Chopra'), ('18', 'Pooja Pandey'), ('19', 'Pinky Jain'), ('20', 'Poonam Gupta'), ('21', 'Rachna Mehrotra'), ('22', 'Ritika Aggarwal'), ('23', 'Ritu Rajpal'), ('24', 'Rohit Bindra'), ('25', 'Ruchika Arora'), ('26', 'Simran Sikka'), ('27', 'Sonam Gupta'), ('28', 'Sudeshna Dutta'), ('29', 'Suman Jain'), ('30', 'Sunita Khurana')], max_length=200),
        ),
    ]
