# Generated by Django 2.1.2 on 2018-10-05 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20171116_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 19, 53, 28, 673385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 5, 19, 53, 28, 674020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fee',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 5, 19, 53, 28, 672068, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='doe',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 10, 5, 19, 53, 28, 672027, tzinfo=utc), null=True),
        ),
    ]
