# Generated by Django 2.1.2 on 2018-10-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20181005_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='doe',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
