# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20170703_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 6, 36, 27, 600058, tzinfo=utc)),
        ),
    ]
