# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20170704_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 6, 37, 29, 707311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 4, 6, 37, 29, 643846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='doe',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 4, 6, 37, 29, 643752, tzinfo=utc)),
        ),
    ]
