# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 18:11
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20170704_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 18, 10, 33, 12408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='adhaar',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='annual_income',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='clas',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 4, 18, 10, 32, 834678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='doe',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 4, 18, 10, 32, 834592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_f',
            field=models.CharField(blank=True, default=9, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_m',
            field=models.CharField(blank=True, default=9, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
    ]
