# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20170704_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 19, 8, 59, 626458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='adhaar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='annual_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 19, 8, 59, 598325, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='doe',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 19, 8, 59, 598165, tzinfo=utc), null=True),
        ),
    ]
