# Generated by Django 2.1.2 on 2018-11-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20181103_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ci',
            name='center_address',
        ),
        migrations.AddField(
            model_name='centre',
            name='ci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.CI'),
        ),
    ]
