# Generated by Django 2.1.2 on 2019-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_auto_20181103_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_for_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_for_year',
            field=models.CharField(choices=[(2019, 2019), (2020, 2020), (2021, 2021)], max_length=256, null=True),
        ),
    ]
