# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20170704_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 6, 6, 46, 44, 412357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='clas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 6, 6, 46, 44, 398869, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='doe',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 7, 6, 6, 46, 44, 398826, tzinfo=utc), null=True),
        ),
    ]
