# Generated by Django 2.1.2 on 2020-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_auto_20191212_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_for_month',
            field=models.CharField(choices=[('1', 'JAN'), ('2', 'FEB'), ('3', 'MAR'), ('4', 'APR'), ('5', 'MAY'), ('6', 'JUN'), ('7', 'JUL'), ('8', 'AUG'), ('9', 'SEP'), ('10', 'OCT'), ('11', 'NOV'), ('12', 'DEC')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_for_year',
            field=models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=256, null=True),
        ),
    ]
